package com.deno4ka.LeetCode.algorithms.easy;

/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e

Explanation:
'e' is the letter that was added.
*/

public class _389_FindTheDifference {

    public _389_FindTheDifference() {
        System.out.println(findTheDifference("abcd", "abcde")); // 'e'
    }

    // (5ms/64.08%)
    public char findTheDifference(String s, String t) {
        if (s == null || s.isEmpty()) {
            return t.charAt(0);
        } else {
            int sum = 0;
            for (char charT : t.toCharArray()) {
                sum += charT;
            }
            for (char charS : s.toCharArray()) {
                sum -= charS;
            }
            return (char) sum;
        }
    }

}